FROM openjdk:8-jre
WORKDIR /
#BINARIES: Add in all necessary application binaries
ADD ./docker-demo-0.0.1-SNAPSHOT.jar docker-demo-0.0.1-SNAPSHOT.jar

EXPOSE 8080

CMD java -jar docker-demo-0.0.1-SNAPSHOT.jar

